title: Freelancer
email: your-email@example.com
description: A Jekyll version of the Freelancer theme by Start Bootstrap
baseurl: "" 
url: "https://yourusername.github.io"
github_username: yourusername

markdown: kramdown
theme: minima
plugins:
  - jekyll-seo-tag

# Personalization
author:
  name: "Start Bootstrap"
  location: "Internet"

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
